version: '3.8'

services:
  api:
    build: .
    container_name: api_petr4
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    depends_on:
      - mlflow
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    container_name: mlflow_server
    ports:
      - "5001:5000"
    working_dir: /app
    volumes:
      - .:/app
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns